### ISSUE TITLE
Not lame, Looks nice! Cheers! 

### ISSUE THREAD

**Issue by amrrs** [bgreenwell/bgreenwell-blogdown#1]
Time to change the sad smiley in the desc ;)

**Comment by bgreenwell** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/94f2aaf9-22c9-49ad-b876-73715887f6b8-1551b314-5e8a-4477-aca2-088c05963111-v1.png?transparent=1&palette=1&width=246)
